# Generated by Django 5.2.4 on 2025-07-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, unique=True)),
                ('access_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoodleAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField()),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AwsMoodleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_user_id', models.CharField(max_length=255)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodle_users', to='project.awsaccount')),
                ('moodle_api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_moodle_users', to='project.moodleapiconfig')),
            ],
            options={
                'unique_together': {('aws_account', 'moodle_api_config')},
            },
        ),
    ]
